services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
#     - "--certificateresolvers.myresolver.acme.httpchallenge=true"
#     - "--certificateresolvers.myresolver.acme.httpchallenge.entrypoint=http"
#     - "--certificateresolvers.myresolver.acme.email=hostmaster@nephometrics.com"
#     - "--certificateresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - traefik.http.middlewares.auth.basicauth.users=admin:${TRAEFIK_PASSWORD}
    ports:
      - "80:80"
#      - "443:443"
    volumes:
     - "./letsencrypt:/letsencrypt"
     - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
     - default

  db:
    image: postgres:16-alpine
    container_name: litellm-postgres
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: litellm_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - litellm_backend
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      STORE_MODEL_IN_DB: "True"
      DATABASE_URL: postgresql://litellm:${POSTGRES_PASSWORD}@db:5432/litellm_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      INFOMANIAK_API_KEY: ${INFOMANIAK_API_KEY}
      
    depends_on:
      db:
        condition: service_healthy
    command: [ "--config", "/app/config.yaml" ]
    restart: always
    networks:
      - litellm_backend
      - default
    labels:
      - traefik.enable=true
      # HTTP Router (Redirects to HTTPS if you have a global redirect, otherwise adjust)
      # - "traefik.http.routers.litellm.rule=Host(`llamas.nephometrics.com`)"
      - traefik.http.routers.litellm.rule=Host(`192.168.0.50`)
      - traefik.http.routers.https.entrypoints=https
      # - traefik.http.routers.litellm.tls=true
      # Certresolver name (change to your specific resolver, e.g., letsencrypt, le, defaults)
      # - "traefik.http.routers.https.tls.certresolver=myresolver"
      # Service Target Port inside the container
      - traefik.http.services.litellm.loadbalancer.server.port=4000

networks:
  litellm_backend:
    internal: true # Keeps DB traffic completely isolated from the internet

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: /home/alpaca/pgdata/litellm_db
      device: /tmp/pgdata/litellm_db
